blogapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# app_name = "blogapp"
urlpatterns = [
    
    path('', views.blog_list,name='bloglist'),
    path('<int:id>',views.single_blog,name='singleblog'),
    path('subcribe/',views.subscribe,name='subscribe')
    
   
]

createuser/urls.py
from django.urls import path
from createuser import views
# SET THE NAMESPACE!
app_name = 'createuser'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('registration/',views.unverified_email,name='register'),
    path('otp/<str:email>',views.verify_otp,name='verify_otp'),
    path('',views.user_login,name='login'),
    path('logout/', views.user_logout,name='logout'),
    path('checkmail/', views.check_email,name='checkmail'),
    path('regenotp/', views.regenrate_otp,name='regenrate_otp'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages.views import flatpage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls'),name ='products'),
    path('login/',include('createuser.urls')),
    path('blogs/',include('blogapp.urls'),name='blogapp'),
    path('dinein/',include('dine_in.urls'),name ='dinein'),
    path('about-us/', flatpage, {'url': '/about/'}, name='about'),
    # path('pages/', include('django.contrib.flatpages.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#urlpatterns = [
    # ... the rest of your URLconf goes here ...

createuser/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email



class unverified_user(models.Model):
    email=models.EmailField()
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    password=models.CharField(max_length=100)
    otp=models.CharField(max_length=5)
    expire_time=models.DateTimeField(null=True,blank=True)

    def __str__(self):
        return self.email

createuser/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser,unverified_user


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        # fields = '__all__'
        fields=('email','first_name','last_name')
        # exclude=('password','user_permissions','groups','date_joined','is_staff','is_superuser','last_login')
        # widgets = {
        #     'email': forms.TextInput(attrs={'class':'input-line full-width'}),
        #     'first_name':forms.TextInput(attrs={'class':'input-line full-width'}),
        #     'last_name':forms.TextInput(attrs={'class':'input-line full-width'}),
        #     'password1':forms.TextInput(attrs={'class':'input-line full-width'}),
        #     'password2':forms.TextInput(attrs={'class':'input-line full-width'})
        # }

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = '__all__'

        

class registerForm(forms.ModelForm):
    password1=forms.CharField(max_length=20,label='confirm password')
    class Meta:
        model = unverified_user	 

        fields =['email','first_name','last_name','password','password1']

        widgets = {
            'email': forms.EmailInput(attrs={'id':'email'}),
        }

    def clean(self):


        super(registerForm, self).clean()
		
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')
        email=self.cleaned_data.get('email')

        if password !=password1:
            self._errors['password'] = self.error_class([
				'both password must be same'])
		
        ql=CustomUser.objects.filter(email=email).first()
        if ql:
            self._errors['email'] = self.error_class([
				'user already exist'])

        return self.cleaned_data
        

createuser/views.py
from django.shortcuts import render,redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import registerForm
from django.contrib import messages
from .models import unverified_user,CustomUser
from  django.contrib.auth.hashers import make_password
import random
from django.conf import settings 
from django.core.mail import send_mail 
from django.http import JsonResponse
import datetime



def send_otp(emailid,otp):
    subject = 'you otp verification code is here'
    message = f'Hi {emailid}, your otp is {otp}.'
    email_from = settings.EMAIL_HOST_USER 
    reciever = [emailid, ] 
    print(email_from,'host')
    print(reciever,'recv')
    send_mail( subject, message, email_from, reciever )
    return True



def unverified_email(request):
    if request.POST:
        form=registerForm(request.POST)
        print(request.POST)
        if form.is_valid():
            print(request.POST)
            req=request.POST
            email=req.get('email')
            number = random.randint(1000,9999)
            print('otp',number)
            print('email unvar',email)
            #if user try to resister again who is not verified user
            try:
            # if True:
                print('try')
                unvar_email=unverified_user.objects.get(email=email)
                print(unvar_email)
                unvar_email.first_name=req.get('first_name')
                unvar_email.last_name=req.get('last_name')
                unvar_email.password=make_password(req.get('password'))
                unvar_email.otp=number


                
                extime=datetime.datetime.now()+ datetime.timedelta(minutes = 5)
                print(datetime.datetime.now())
                print(extime)
                unvar_email.expire_time=extime



                unvar_email.save()
            #if user try to register 1st time
            except:
                print('except')
                data = form.save(commit = False)

                print(data.password)
                print(make_password(data.password))
                print(number)
                data.otp=number
                data.password=make_password(data.password)


       
                extime=datetime.datetime.now()+ datetime.timedelta(minutes = 5)
                print(datetime.datetime.now())
                print(extime)
                data.expire_time=extime
                data.save() 
            #send massege
            send_otp(email,number)

            
            return redirect('createuser:verify_otp',email=request.POST.get('email')) #createuser.verify_otp
        else:
            return render(request, "createuser/resistration1.html", {'form':form}) 
    form=registerForm()
    return render(request,'createuser/resistration1.html',{'form':form})




def check_email(request):
    response={}
    if request.method == 'GET':
        data=request.GET.get('email')
        print(data)
        if data:
            ql=CustomUser.objects.filter(email=data).first()
            print(ql)
            if ql:
                response['massege']='exist'
            else:
                response['massege']='not exist'
        
    return JsonResponse(response)



def verify_otp(request,email):
    if request.POST:
        print('email otp',email)
        print(request.POST.get('otp'))
        
        check_otp=request.POST.get('otp')
        unvar_email=unverified_user.objects.get(email=request.POST.get('email'))
        if unvar_email.otp == check_otp:
            
            from django.utils import timezone
            now = timezone.now()

            print(now)
            print(datetime.datetime.now())
            if now < unvar_email.expire_time:
                createuser=CustomUser.objects.create(email=unvar_email.email,first_name=unvar_email.first_name,last_name=unvar_email.last_name,password=unvar_email.password)
                print(createuser)
                unvar_email.delete()
                return redirect('index')
            else:
                massege='otp is expired'
        else:
                massege='given otp is not valid, please give valid otp'
        return render(request,'createuser/otp_varification.html',{'email':request.POST.get('email'),'massege':massege})


        print(email_data.otp)
    return render(request,'createuser/otp_varification.html',{'email':email})




import pytz

utc=pytz.UTC

def regenrate_otp(request):
    response={}
    if request.method == 'GET':
        email=request.GET.get('email')
        print(email)
        if email:
            unvar_email=unverified_user.objects.get(email=email)
            # generate otp
            number = random.randint(1000,9999)
            unvar_email.otp=number
            extime=datetime.datetime.now()+ datetime.timedelta(minutes = 5)
            print(datetime.datetime.now())
            print(extime)
            
            unvar_email.expire_time=extime.replace(tzinfo=utc)
            
            if send_otp(email,number):
                unvar_email.save()

                response['massege']='otp re-genrated'              
    return JsonResponse(response)




@login_required(login_url='createuser:login')
def user_logout(request):
    
    logout(request)
    return redirect('index')


                         

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect('index')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'createuser/login.html')

templates/createuser/login.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/createuser/login.css' %}">

  <title>Войти</title>
</head>
<style>

</style>
<body>
  <div class='bold-line'></div>
<div class='container'>
  <div class='window'>
    <div class='overlay'></div>
    <div class='content'>
      <div class='welcome'>Войти!</div>
      <div class='subtitle'>Введите ваш email и пароль для того, чтобы войти в свой аккаунт.</div>
      <form action="" method="POST">
        <div class='input-fields'>
          {%csrf_token%}
          <!-- <input type='text' placeholder='Username' class='input-line full-width'></input> -->
          <input type='email' name="email" placeholder='Email' class='input-line full-width'></input>
          <input type='password' name="password" placeholder='Пароль' class='input-line full-width'></input>
  
        </div>
        <div><button type="submit" class='ghost-round full-width'>Войти</button></div>
      </form>
      <div class='spacing'><a href="{%url 'createuser:register'%}">создать новый аккаунт? </a> </div>
    </div>
  </div>
</div>
  
</body>
</html>


templates/createuser/otp_varification.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<link rel="stylesheet" href="{% static 'css/createuser/otp_varification.css' %}">

</head>

<body>
    	

<form action="#" method="post">
    {%csrf_token%}
	<h2>enter otp</h2>
	<p hidden >

		<input type="text" name='email' id="email" value={{email}} >
	</p>
          <p >
              <label for="otp" class="floatLabel">Enter your Otp</label>
              <input id="otp" name="otp" type="text">
          </p>
          
	  <!-- {{email}} -->
	  <p class="massege">opt has been sent on your email, it will expire in 5 minutes</p>
	  {% if massege%}
	  <p class="massege" style="color: red;">{{massege}} </p>
	  {%endif%}

          <p>
              <input type="submit" value="Cofirm" id="submit">
		  </p>
		  <p {% if massege != "otp is expired" %} hidden 
		 	{%endif%} 
		  >
			<input type="button" value="Regenrate Otp" id="otp-regenrate">
			<p id="regenrate-massage" style="font-size: medium;"></p>
		</p>
	  </form>


	  
	  <script>
		  var searchRequest = null;
		  email=document.getElementById('email').value
		console.log(email)

$(function () {
    var searchRequest = null;

    $("#otp-regenrate").click(function () {
        email=document.getElementById('email').value
		console.log(email)
        regen=document.getElementById('regenrate-massage')
         regen.innerHTML =''

        
        
        
        
            if (searchRequest != null) 
                searchRequest.abort();
               

            searchRequest = $.ajax({
                type: "GET",
                url: "{%url 'createuser:regenrate_otp'%}",
                data: {
                    'email' : email
                },
                dataType: "text",
                success: function(msg){
                    var obj = JSON.parse(msg);
                    console.log(obj.massege)
                    
                    
                    if (obj.massege== 'otp re-genrated'){
					regen=document.getElementById('regenrate-massage')
                    regen.innerHTML ='Otp is regenerated, please check your mail'
                    regen.style.display='block'
                    }
                    else{
                        regen.innerHTML ='Something went wrong, please register again'
                    }
                    console.log(regen)
                   
                }
            });
        
    });
});

	  </script>
	  
</body>
</html>

templates/createuser/resistration1.html
{%load static%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/createuser/registration.css' %}">

    <title>Регистрация</title>
</head>

<body>
    	

<form action="#" method="post">
    {%csrf_token%}
    <h2>Зарегистрироваться</h2>
   

          <p>
              
             
              {{ form.non_field_errors }}
                  {{ form.first_name.errors }}
                  <label class="floatLabel" for="{{ form.first_name.id_for_label }}">Имя</label>
                  {{ form.first_name }}
          </p>

            <p>

                
              <label class="floatLabel" for="{{ form.last_name.id_for_label }}">Фамилия</label>
              {{ form.last_name }}
              {{ form.last_name.errors }}
            </p>
              
             <p>

               <label class="floatLabel" for="{{ form.email.id_for_label }}">Email адрес:</label>
               {{ form.email }}
               
                 {{ form.email.errors }}
               <span id="not_valid_email" ></span>
            </p>
            <p>

                {{ form.password.errors }}
                <label class="floatLabel" for="{{ form.password.id_for_label }}">Пароль</label>
                {{ form.password }}
                <span>Введите пароль более 8 символов</span>
           </p>

           <p>

            {{ form.password1.errors }}
            <label class="floatLabel" for="{{ form.password1.id_for_label }}">Повторите пароль</label>
            {{ form.password1 }}
            <span>Ваши пароли не совпадают</span>
       </p>  
         
          
          <p>
              <input type="submit" value="Создать мой аккаунт" id="submit">
          </p>
      </form>


      <script>
////email validation////////////////
var searchRequest = null;

$(function () {
    var searchRequest = null;

    $("#{{ form.email.id_for_label }}").keyup(function () {
        error_msg=document.getElementById('not_valid_email')
        error_msg.innerHTML =''

        
        var that = this;
        console.log(that);
        email_input = $(this).val();
        console.log(email_input,'value')
        var mailformat = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
        
        if(email_input.match(mailformat))
        {
            console.log(email_input,'its email')
            if (searchRequest != null) 
                searchRequest.abort();
                console.log(email_input,'its email abort')

            searchRequest = $.ajax({
                type: "GET",
                url: "{%url 'createuser:checkmail'%}",
                data: {
                    'email' : email_input
                },
                dataType: "text",
                success: function(msg){
                    var obj = JSON.parse(msg);
                    console.log(obj.massege)
                    
                    console.log(error_msg)
                    if (obj.massege== 'exist'){

                    error_msg.innerHTML ='user with this email already exist'
                    error_msg.style.display='block'
                    }
                    else{
                        error_msg.innerHTML =''
                    }
                    console.log(error_msg)
                   
                }
            });
        }
    });
});



//////////////pasword validation////////////////////

          //Problem: Hints are shown even when form is valid
//Solution: Hide and show them at appropriate times
var $password = $("#id_password");
var $confirmPassword = $("#id_password1");



//Hide hints
$("form span").hide();

function isPasswordValid() {
  return $password.val().length > 8;
}

function arePasswordsMatching() {
  return $password.val() === $confirmPassword.val();
}

function canSubmit() {
  return isPasswordValid() && arePasswordsMatching();
}

function passwordEvent(){
    //Find out if password is valid  
    if(isPasswordValid()) {
      //Hide hint if valid
      $password.next().hide();
    } else {
      //else show hint
      $password.next().show();
    }
}

function confirmPasswordEvent() {
  //Find out if password and confirmation match
  if(arePasswordsMatching()) {
    //Hide hint if match
    $confirmPassword.next().hide();
  } else {
    //else show hint 
    $confirmPassword.next().show();
  }
}

function enableSubmitEvent() {
  $("#submit").prop("disabled", !canSubmit());
}

//When event happens on password input
$password.focus(passwordEvent).keyup(passwordEvent).keyup(confirmPasswordEvent).keyup(enableSubmitEvent);

//When event happens on confirmation input
$confirmPassword.focus(confirmPasswordEvent).keyup(confirmPasswordEvent).keyup(enableSubmitEvent);

enableSubmitEvent();
      </script>
</body>
</html>