blogapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
# app_name = "blogapp"
urlpatterns = [
    
    path('', views.blog_list,name='bloglist'),
    path('<int:id>',views.single_blog,name='singleblog'),
    path('subcribe/',views.subscribe,name='subscribe')
    
   
]

createuser/urls.py
from django.urls import path
from createuser import views
# SET THE NAMESPACE!
app_name = 'createuser'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    path('registration/',views.unverified_email,name='register'),
    path('otp/<str:email>',views.verify_otp,name='verify_otp'),
    path('',views.user_login,name='login'),
    path('logout/', views.user_logout,name='logout'),
    path('checkmail/', views.check_email,name='checkmail'),
    path('regenotp/', views.regenrate_otp,name='regenrate_otp'),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.flatpages.views import flatpage


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls'),name ='products'),
    path('login/',include('createuser.urls')),
    path('blogs/',include('blogapp.urls'),name='blogapp'),
    path('dinein/',include('dine_in.urls'),name ='dinein'),
    path('about-us/', flatpage, {'url': '/about/'}, name='about'),
    # path('pages/', include('django.contrib.flatpages.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#urlpatterns = [
    # ... the rest of your URLconf goes here ...

templates/about.html
{%extends 'base.html'%}

{%block title%}
{{ flatpage.title }}

{%endblock%}



{%block activeclass_about%}

class="active"

{%endblock%}


{%block content%}
<div class="flex justify-center" style="margin: 5% 10%;flex-direction: column;" >

    <h1 class="section-heading" style="margin-top: 20px;"> {{ flatpage.title }}</h1>
    
   

        <p style="margin: 20px;">&nbsp;&nbsp;&nbsp;{{ flatpage.content }} {%lorem 20 p random %}  </p>
    </div>


{%endblock%}

templates/products1.html
{% extends 'base.html' %}

{%load static%}

{%block title%}
products page

{%endblock%}


{%block activeclass_prod%}
class="active"

{%endblock%}


{% block content%}
{%load static%}




<!-- ///////////////////////////////////// -->


<!-- //////////// -->




<!-- style="display: flex;
    padding: 1rem;" -->
    {% for category in categories %}
<h1 class="section-heading" style="margin: 20px;margin-top: 5%;"> {{category}} </h1>
    <div class="conta justify-center" 
    style="display: flex;
flex-wrap: wrap;


 "
    >
    {% for product in category.get_products %}
    <div class="food-card magic-shadow-sm prod-card" style="margin: 20px 5%;" >

                                    <div class="product-image flex items-center justify-center " style="margin: 5% 20%;">
                                        <div style="background:url({{product.pimage.url}}) no-repeat center;width: 300px;padding-top: 200px;background-size: contain;
                                        border-radius: 50%;
                                        "></div>
                                        <!-- <img  src="{{i.pimage.url}}" alt=""> -->
                                    </div>
                                    <hr>
                                    <div>
                                        <h2 class="text-center">{{product.pname}}</h2>
                                        <h5 class="text-center">{{product.category}} </h5>
                                        <!-- <div class="stars flex justify-center items-center">
                                            <img src="{% static 'icons/start-filled.svg' %}" alt="">
                                            <img src="{% static 'icons/start-filled.svg' %}" alt="">
                                            <img src="{% static 'icons/start-filled.svg' %}" alt="">
                                            <img src="{% static 'icons/star-grey.svg' %}" alt="">
                                            <img src="" alt="">
                                        </div> -->
                                        <div class="price text-center">
                                            {{product.price}} Сум
                                        </div>
                                        <!-- <form class="cartform" id="{{i.pname}}">
                                            {% csrf_token %}
                                            <input type="text" name="product" value="{{i.pname}}" hidden /> -->
                                            {%if not user.is_authenticated%}
                                            <a href="{%url 'createuser:login' %}" style="text-decoration: none;">
                                        <div class="flex justify-center">
                                            <button value="submit" class="cartform" id="{{product.id}}">
                                                <img src="{% static 'icons/cart-2.svg' %}" alt="">
                                                <span >В корзину</span>
                                            </button>
                                        </div>
                                    </a>
                                            {%else%}
                                            <div class="flex justify-center">

                                            <button value="submit" class="cartform" id="{{product.id}}">

                                            <img src="{% static 'icons/cart-2.svg' %}" alt="">
                                            <span>В корзину</span>
                                        </button>
                                    </div>
                                            {%endif%}
                                    <!-- </form> -->
                                    </div>
                                </div>
                                {%endfor%}
                            </div>
                            {%endfor%}

                            
                              
                            

                               
                               
{%endblock%}

templates/search.html
{% extends 'base.html' %}

{% block content%}
{%load static%}
{%if food%}
<h1 class="section-heading" style="margin: 40px;">Items for : {{searchitem}}</h1>
<div class="cont justify-center" 
style="display: flex;
flex-wrap: wrap;">
{% for i in food %}
    <div class="food-card magic-shadow-sm prod-card" style="margin: 20px 5%;">
            <div class="product-image flex items-center justify-between " style="margin: 5% 20%;">
                <div style="background:url({{i.pimage.url}}) no-repeat center;width: 300px;
                padding-top: 200px;background-size: contain;
                border-radius: 50%;
                "></div>
            <!-- <img src="{{i.pimage.url}}" alt=""> -->
        </div>
        <hr>
        <div>
            <h2 class="text-center">{{i.pname}}</h2>
            <h5 class="text-center">{{i.category}} </h5>
            <!-- <div class="stars flex justify-center items-center">
                <img src="{% static 'icons/start-filled.svg' %}" alt="">
                <img src="{% static 'icons/start-filled.svg' %}" alt="">
                <img src="{% static 'icons/start-filled.svg' %}" alt="">
                <img src="{% static 'icons/star-grey.svg' %}" alt="">
                <img src="" alt="">
            </div> -->
            <div class="price text-center">
                $ {{i.price}}
            </div>
            <!-- <form class="cartform" id="{{i.pname}}">
                {% csrf_token %} -->
                <input type="text" name="product" value="{{i.id}}" hidden />
        <div class="flex justify-center">  
            <button value="submit" class="cartform" id="{{i.id}}">
                <img src="{% static 'icons/cart-2.svg' %}" alt="">
                <span>В корзину</span>
            </button>
        </div>
        <!-- </form> -->
        </div>
    </div>
    {%endfor%}
    </div>
    {%else%}
    <h1 class="section-heading" style="margin: 40px;">No item available for : {{searchitem}}</h1>
{%endif%}
{%endblock%}